### ISSUE TITLE
Define the high level features you want the site to have 

### ISSUE THREAD

**Issue by adriant172** [adriant172/CS50_Final_Project#1]
- User can register an account
- User can select cuisine preferences for their account
- Can set a budget per a weekly/or daily basis
- The app will be able to grab the average price of food items based on the users defined location
- Generate recipe suggestions to the user as per their cuisine preferences and the currently set budget
- User can press a button a recipe that indicates that they have cooked a recipe, as well as provide a rating on a recipe 
- User can save/tab a recipe for quick access, that can be possibly exported for ease of access
- Users can also share recipes
- User gain points for confirming that they have successfully cooked a dish as well as for sharing recipes

**Comment by psyrus** [comment]
Points

- Would recommend starting off with either a weekly OR a daily budget system... probably daily (and then have it auto calculate the weekly one later if desired)
- What does "cuisine preferences" mean?
- When you say "grab food prices" what does that mean? From a DB?
- Wouldn't just the rating system interaction imply that they used the recipe?
- Where are recipes shared to? Facebook?

**Comment by adriant172** [comment]
> Points
> 
> * Would recommend starting off with either a weekly OR a daily budget system... probably daily (and then have it auto calculate the weekly one later if desired)
> * What does "cuisine preferences" mean?
> * When you say "grab food prices" what does that mean? From a DB?
> * Wouldn't just the rating system interaction imply that they used the recipe?
> * Where are recipes shared to? Facebook?

- I agree that daily budget would be easier to manage from the beginning 
- cuisine preferences refers to types of cuisine  like "Italian" or "Chinese" etc.., I was also thinking of including more general types as well ie. pasta, stews, salads etc..
- "grab food prices" means possibly finding from some external sources that might provided aggregate food prices in different locations ( not really sure will have to do some additional research regarding this ) 
- Regarding the rating system that is a valid point
- Possibly a social media integration , it perhaps would it be easier to keep track of the count of shares if it was email sent from the app instead ?

**Comment by psyrus** [comment]
- So as long as you design your system around "themes/countries" instead of ingredients you should be fine then
- I doubt you're going to find something like that. The best you can hope for is likely doing something like finding the American prices and then automating a PPP calculation between countries... but I would recommend just having the ability to submit a per-gram cost for a given item, and then your system could aggregate those prices from user submissions. Totally up to you though, if you find something to do that work for you, great.
- Sharing to social media is going to be a load of extra work IMHO, but if you want to go in that direction, it's not impossible

**Comment by adriant172** [comment]
- Task completed
